import Link from "next/link";

import { EmptyState, ModulePlaceholder } from "@/components/ui";
import { PrimaryShowroomRegistrationUploadFields } from "@/components/customers/primary-showroom-registration-upload-fields";
import { ConfirmRemoveButton } from "@/components/ui/confirm-remove-button";
import { dateLabel } from "@/lib/formatters";

type Registration = { created_at: string; documentCount: number; id: string; imageCount: number; purpose: string; registration_name: string; };
type FileLink = { id: string; original_file_name: string; signed_url: string | null; };
const purposeLabel: Record<string, string> = { initial_participating: "Initial Participating", program_renewal: "Program Renewal", program_audit: "Program Audit", other: "Other" };

export function PrimaryShowroomRegistrationTab({ addHref, customerId, enrollmentId, registrations }: { addHref: string; customerId: string; enrollmentId: string; registrations: Registration[] }) {
  const detailHref = (id: string) => `/?module=primary-showroom-registration&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_registration=${id}`;
  return <article className="data-section"><div className="section-title"><div><h3>Registration / Renewal</h3><p>Participation agreements, renewal materials, audit reports, and floor-display images.</p></div><Link className="small-action" href={addHref}>Add Documents</Link></div>{registrations.length === 0 ? <EmptyState text="No registration, renewal, or audit packages have been added." /> : <div className="table-wrap"><table><thead><tr><th>Purpose</th><th>Name</th><th>Documents</th><th>Images</th><th>Created</th></tr></thead><tbody>{registrations.map((registration) => <tr key={registration.id}><td>{purposeLabel[registration.purpose] ?? registration.purpose}</td><td><Link className="record-link" href={detailHref(registration.id)}>{registration.registration_name}</Link></td><td><Link className="text-action" href={detailHref(registration.id)}>{registration.documentCount} document{registration.documentCount === 1 ? "" : "s"}</Link></td><td><Link className="text-action" href={detailHref(registration.id)}>{registration.imageCount} image{registration.imageCount === 1 ? "" : "s"}</Link></td><td>{dateLabel(registration.created_at)}</td></tr>)}</tbody></table></div>}</article>;
}

export function PrimaryShowroomRegistrationAddPage({ customerId, enrollmentId, error, saveAction }: { customerId?: string; enrollmentId?: string; error?: string; saveAction: (formData: FormData) => void | Promise<void> }) {
  if (!customerId || !enrollmentId) return <ModulePlaceholder moduleName="Adding registration documents requires a selected Primary Showroom" />;
  const backHref = `/?module=primary-showroom&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_tab=registration`;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Primary Showroom</span><h2>Add Registration / Renewal Documents</h2><p>Add one named package of agreements, audit documents, and floor images.</p></div><Link className="secondary-action secondary-action--light" href={backHref}>Back to Registration / Renewal</Link></section>{error ? <div className="form-alert">{decodeURIComponent(error)}</div> : null}<form action={saveAction} className="customer-form"><input name="customer_id" type="hidden" value={customerId} /><input name="enrollment_id" type="hidden" value={enrollmentId} /><fieldset><legend>Package Details</legend><div className="form-grid"><label>Name<input name="registration_name" required /></label><label>Purpose<select defaultValue="" name="purpose" required><option disabled value="">Select purpose</option><option value="initial_participating">Initial Participating</option><option value="program_renewal">Program Renewal</option><option value="program_audit">Program Audit</option><option value="other">Other</option></select></label><PrimaryShowroomRegistrationUploadFields accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt" label="Documents" name="document_files" /><PrimaryShowroomRegistrationUploadFields accept="image/*" label="Images" name="image_files" /></div><p className="fieldset-note">Add documents, images, or both. Use the add controls to include as many files as needed; each file remains available from this package.</p></fieldset><div className="form-actions"><button className="primary-action" type="submit">Save Documents</button><Link className="secondary-action secondary-action--light" href={backHref}>Cancel</Link></div></form></section>;
}

export function PrimaryShowroomRegistrationAttachmentAddPage({ attachmentType, customerId, enrollmentId, error, registrationId, saveAction }: { attachmentType?: string; customerId?: string; enrollmentId?: string; error?: string; registrationId?: string; saveAction: (formData: FormData) => void | Promise<void> }) {
  if (!customerId || !enrollmentId || !registrationId || (attachmentType !== "document" && attachmentType !== "image")) return <ModulePlaceholder moduleName="Adding files requires a selected registration package" />;
  const isImage = attachmentType === "image";
  const backHref = `/?module=primary-showroom-registration&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_registration=${registrationId}`;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Primary Showroom Registration</span><h2>Add {isImage ? "Images" : "Documents"}</h2><p>Add one or more files to this registration package.</p></div><Link className="secondary-action secondary-action--light" href={backHref}>Back to Registration</Link></section>{error ? <div className="form-alert">{decodeURIComponent(error)}</div> : null}<form action={saveAction} className="customer-form"><input name="customer_id" type="hidden" value={customerId} /><input name="enrollment_id" type="hidden" value={enrollmentId} /><input name="registration_id" type="hidden" value={registrationId} /><input name="attachment_type" type="hidden" value={attachmentType} /><fieldset><legend>{isImage ? "Images" : "Documents"}</legend><PrimaryShowroomRegistrationUploadFields accept={isImage ? "image/*" : ".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt"} label={isImage ? "Images" : "Documents"} name="files" /><p className="fieldset-note">Use the add control to include as many files as needed.</p></fieldset><div className="form-actions"><button className="primary-action" type="submit">Save {isImage ? "Images" : "Documents"}</button><Link className="secondary-action secondary-action--light" href={backHref}>Cancel</Link></div></form></section>;
}

export async function PrimaryShowroomRegistrationDetailPage({ customerId, deleteAttachmentAction, enrollmentId, registrationId, loadRegistration }: { customerId?: string; deleteAttachmentAction: (formData: FormData) => void | Promise<void>; enrollmentId?: string; registrationId?: string; loadRegistration: (customerId: string, enrollmentId: string, registrationId: string) => Promise<{ createdAt: string; documents: FileLink[]; images: FileLink[]; name: string; purpose: string; }>; }) {
  if (!customerId || !enrollmentId || !registrationId) return <ModulePlaceholder moduleName="Viewing registration documents requires a selected package" />;
  const registration = await loadRegistration(customerId, enrollmentId, registrationId);
  const backHref = `/?module=primary-showroom&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_tab=registration`;
  const addHref = (attachmentType: "document" | "image") => `/?module=primary-showroom-registration-attachment-add&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_registration=${registrationId}&attachment_type=${attachmentType}`;
  const fileList = (files: FileLink[], empty: string) => files.length ? <div className="compact-list">{files.map((file) => <div className="compact-row" key={file.id}><strong>{file.original_file_name}</strong><div className="inline-actions">{file.signed_url ? <a className="text-action" href={file.signed_url} rel="noreferrer" target="_blank">Open</a> : <span>Unavailable</span>}<form action={deleteAttachmentAction}><input name="customer_id" type="hidden" value={customerId} /><input name="enrollment_id" type="hidden" value={enrollmentId} /><input name="registration_id" type="hidden" value={registrationId} /><input name="registration_attachment_id" type="hidden" value={file.id} /><ConfirmRemoveButton label="Delete" message={`Delete ${file.original_file_name}? This cannot be undone.`} title="Delete file?" variant="text" /></form></div></div>)}</div> : <EmptyState text={empty} />;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Primary Showroom Registration</span><h2>{registration.name}</h2><p>{purposeLabel[registration.purpose] ?? registration.purpose} · {dateLabel(registration.createdAt)}</p></div><Link className="secondary-action secondary-action--light" href={backHref}>Back to Registration / Renewal</Link></section><section className="detail-grid"><article className="data-section"><div className="section-title"><h3>Documents</h3><div className="section-actions"><Link className="text-action" href={addHref("document")}>Add</Link><span>{registration.documents.length}</span></div></div>{fileList(registration.documents, "No documents were uploaded.")}</article><article className="data-section"><div className="section-title"><h3>Images</h3><div className="section-actions"><Link className="text-action" href={addHref("image")}>Add</Link><span>{registration.images.length}</span></div></div>{fileList(registration.images, "No images were uploaded.")}</article></section></section>;
}
