import Link from "next/link";

import { EmptyState, ModulePlaceholder, StatusBadge } from "@/components/ui";
import { dateLabel, numberFormatter } from "@/lib/formatters";

type Display = { customer_po_number_snapshot: string | null; display_discount_percent_snapshot: number | null; display_shipped_date_snapshot: string | null; display_status: string; id: string; minimum_floor_through_date: string | null; product_name_snapshot: string | null; sku_snapshot: string; };
type Preview = { contactName: string | null; displays: Display[]; salesAgencyName: string | null; salesRepName: string | null; showroomName: string; };
type SnapshotDetail = Preview & { snapshotDate: string; snapshotName: string; };

function DisplayTable({ displays }: { displays: Display[] }) {
  return displays.length === 0 ? <EmptyState text="No active display items will be included." /> : <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Name</th><th>Original PO</th><th>Discount</th><th>Shipped Date</th><th>Mature Date</th><th>Status</th></tr></thead><tbody>{displays.map((display) => <tr key={display.id}><td>{display.sku_snapshot}</td><td>{display.product_name_snapshot ?? "Display item"}</td><td>{display.customer_po_number_snapshot ?? "Not set"}</td><td>{display.display_discount_percent_snapshot ?? 0}%</td><td>{dateLabel(display.display_shipped_date_snapshot)}</td><td>{dateLabel(display.minimum_floor_through_date)}</td><td><StatusBadge tone={display.display_status === "active" ? "good" : "neutral"} value={display.display_status === "active" ? "On floor" : display.display_status} /></td></tr>)}</tbody></table></div>;
}

export async function PrimaryShowroomSnapshotCreatePage({ customerId, enrollmentId, error, loadPreview, saveAction }: { customerId?: string; enrollmentId?: string; error?: string; loadPreview: (customerId: string, enrollmentId: string) => Promise<Preview>; saveAction: (formData: FormData) => void | Promise<void> }) {
  if (!customerId || !enrollmentId) return <ModulePlaceholder moduleName="Creating a snapshot requires a selected Primary Showroom" />;
  const preview = await loadPreview(customerId, enrollmentId);
  const backHref = `/?module=primary-showroom&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_tab=history`;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Primary Showroom</span><h2>Create Snapshot</h2><p>{preview.showroomName}</p></div><Link className="secondary-action secondary-action--light" href={backHref}>Back to Current &amp; History</Link></section>{error ? <div className="form-alert">{decodeURIComponent(error)}</div> : null}<form action={saveAction} className="customer-form"><input name="customer_id" type="hidden" value={customerId} /><input name="enrollment_id" type="hidden" value={enrollmentId} /><fieldset><legend>Snapshot Details</legend><div className="form-grid"><label>Snapshot Name<input defaultValue={`Snapshot - ${new Date().toISOString().slice(0, 10)}`} name="snapshot_name" required /></label></div><div className="detail-grid"><article className="info-panel"><h3>Primary Showroom Contact</h3><p>{preview.contactName ?? "Not set"}</p></article><article className="info-panel"><h3>Sales Coverage</h3><p>{preview.salesAgencyName ?? "Not assigned"}<br />{preview.salesRepName ?? "No sales rep assigned"}</p></article></div></fieldset><article className="data-section"><div className="section-title"><h3>Active Displays to Snapshot</h3><span>{numberFormatter.format(preview.displays.length)}</span></div><DisplayTable displays={preview.displays} /></article><div className="form-actions"><button className="primary-action" type="submit">Confirm and Save Snapshot</button><Link className="secondary-action secondary-action--light" href={backHref}>Cancel</Link></div></form></section>;
}

export async function PrimaryShowroomSnapshotDetailPage({ customerId, enrollmentId, snapshotId, loadSnapshot }: { customerId?: string; enrollmentId?: string; snapshotId?: string; loadSnapshot: (customerId: string, enrollmentId: string, snapshotId: string) => Promise<SnapshotDetail> }) {
  if (!customerId || !enrollmentId || !snapshotId) return <ModulePlaceholder moduleName="Viewing a snapshot requires a selected Primary Showroom snapshot" />;
  const snapshot = await loadSnapshot(customerId, enrollmentId, snapshotId);
  const backHref = `/?module=primary-showroom&customer=${customerId}&primary_showroom=${enrollmentId}&primary_showroom_tab=history`;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Primary Showroom Snapshot</span><h2>{snapshot.snapshotName}</h2><p>{dateLabel(snapshot.snapshotDate)}</p></div><Link className="secondary-action secondary-action--light" href={backHref}>Back to Snapshots</Link></section><section className="detail-grid"><article className="info-panel"><h3>Primary Showroom Contact</h3><p>{snapshot.contactName ?? "Not set"}</p></article><article className="info-panel"><h3>Sales Coverage</h3><p>{snapshot.salesAgencyName ?? "Not assigned"}<br />{snapshot.salesRepName ?? "No sales rep assigned"}</p></article></section><article className="data-section"><div className="section-title"><h3>Snapshot Contents</h3><span>{numberFormatter.format(snapshot.displays.length)}</span></div><DisplayTable displays={snapshot.displays} /></article></section>;
}
