import Link from "next/link";
import { dateLabel, numberFormatter } from "@/lib/formatters";
import { ContainerLoadingSheetControls } from "./container-loading-sheet-controls";

type Container = { id: string; container_number: string; booking_number: string | null; shipping_agency: string | null; vessel_name: string | null; etd: string | null; eta: string | null; arrival_port: string | null };
type Line = { id: string; vendor_id: string; vendor_name: string; vendor_email: string | null; po_number: string; sku: string; name: string; quantity_packed: number; packing_dimensions: string[]; unit_cbm: number | null; line_cbm: number | null; quantity_boxes: number };

const cbm = (value: number | null) => value === null ? "Not set" : `${value.toLocaleString("en-US", { minimumFractionDigits: 3, maximumFractionDigits: 6 })} m³`;

export function ContainerLoadingSheetPage({ container, lines, selectedVendorId }: { container: Container | null; lines: Line[]; selectedVendorId?: string }) {
  if (!container) return <section className="dashboard-panel"><div className="form-alert">Container was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;
  const baseHref = `/?module=container-loading-sheets&container=${container.id}`;
  const groups = new Map<string, { id: string; name: string; email: string | null; lines: Line[] }>();
  for (const line of lines) { const group = groups.get(line.vendor_id) ?? { id: line.vendor_id, name: line.vendor_name, email: line.vendor_email, lines: [] }; group.lines.push(line); groups.set(line.vendor_id, group); }
  const vendors = [...groups.values()].sort((left, right) => left.name.localeCompare(right.name));
  const selectedVendor = selectedVendorId ? groups.get(selectedVendorId) ?? null : null;

  if (selectedVendor) {
    const totals = { boxes: selectedVendor.lines.reduce((sum, line) => sum + line.quantity_boxes, 0), cbm: selectedVendor.lines.reduce((sum, line) => sum + (line.line_cbm ?? 0), 0), quantity: selectedVendor.lines.reduce((sum, line) => sum + line.quantity_packed, 0) };
    return <section className="quote-document-page"><div className="quote-document-controls"><Link className="secondary-action" href={baseHref}>Back to Vendor Loading Sheets</Link><ContainerLoadingSheetControls containerNumber={container.container_number} recipientEmail={selectedVendor.email} vendorName={selectedVendor.name} /></div><article className="quote-document"><header className="quote-document-header"><div><span className="eyebrow">Terracotta Designs and Kanova &amp; Co.</span><h2>Container Loading Sheet</h2><p>{selectedVendor.name}</p></div><dl><div><dt>Container</dt><dd>{container.container_number}</dd></div><div><dt>Booking Number</dt><dd>{container.booking_number || "Not set"}</dd></div><div><dt>Shipping Agency</dt><dd>{container.shipping_agency || "Not set"}</dd></div><div><dt>Vessel</dt><dd>{container.vessel_name || "Not set"}</dd></div><div><dt>Expected Departure</dt><dd>{dateLabel(container.etd)}</dd></div><div><dt>Expected Arrival</dt><dd>{dateLabel(container.eta)}</dd></div><div><dt>Arrival Port</dt><dd>{container.arrival_port || "Not set"}</dd></div></dl></header><table className="quote-document-table"><thead><tr><th>PO #</th><th>SKU</th><th>Product</th><th>Qty to Load</th><th>Packing W × D × H</th><th>Unit CBM</th><th>Line CBM</th></tr></thead><tbody>{selectedVendor.lines.map((line) => <tr key={line.id}><td>{line.po_number}</td><td>{line.sku}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_packed)}</td><td>{line.packing_dimensions.length ? line.packing_dimensions.map((dimensions) => <div key={dimensions}>{dimensions}</div>) : "Not set"}</td><td>{cbm(line.unit_cbm)}</td><td>{cbm(line.line_cbm)}</td></tr>)}</tbody></table><div className="quote-document-total"><span>Total Qty to Load</span><strong>{numberFormatter.format(totals.quantity)}</strong></div><div className="quote-document-total"><span>Total Qty of Boxes</span><strong>{numberFormatter.format(totals.boxes)}</strong></div><div className="quote-document-total"><span>Total CBM</span><strong>{cbm(totals.cbm)}</strong></div></article></section>;
  }

  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Container Shipment</span><h2>Vendor Loading Sheets</h2><p>{container.container_number} · Select a vendor to download or email its product loading list.</p></div><Link className="secondary-action secondary-action--light" href={`/?module=container-detail&container=${container.id}`}>Back to Container</Link></section><article className="data-section"><div className="section-title"><h3>Vendors in Container</h3><span>{vendors.length}</span></div>{vendors.length ? <div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Email</th><th>Product Lines</th><th>Qty to Load</th><th>CBM</th><th>Action</th></tr></thead><tbody>{vendors.map((vendor) => <tr key={vendor.id}><td>{vendor.name}</td><td>{vendor.email || "Not set"}</td><td>{numberFormatter.format(vendor.lines.length)}</td><td>{numberFormatter.format(vendor.lines.reduce((sum, line) => sum + line.quantity_packed, 0))}</td><td>{cbm(vendor.lines.reduce((sum, line) => sum + (line.line_cbm ?? 0), 0))}</td><td><Link className="text-action" href={`${baseHref}&loading_vendor=${vendor.id}`}>Export Loading Sheet</Link></td></tr>)}</tbody></table></div> : <p className="fieldset-note">No vendor products have been loaded into this container.</p>}</article></section>;
}
