"use client";

import { useState, useTransition } from "react";

type Result = { destination?: string; error?: string };

export function ContainerEditor({ error, saveAction }: { error?: string; saveAction: (formData: FormData) => Promise<Result> }) {
  const [formError, setFormError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Container Shipment</span><h2>Create Container</h2><p>Record shipping details first, then add products from active purchase orders.</p></div><a className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</a></section>{error || formError ? <div className="form-alert">{formError ?? decodeURIComponent(error ?? "")}</div> : null}<form className="customer-form" onSubmit={(event) => { event.preventDefault(); const formData = new FormData(event.currentTarget); startTransition(async () => { setFormError(null); const result = await saveAction(formData); if (result.error) setFormError(result.error); else if (result.destination) window.location.assign(result.destination); }); }}><fieldset><legend>Shipping Details</legend><div className="form-grid"><label>Shipping Agency Name<input name="shipping_agency" /></label><label>Shipping Agent Contact Email<input name="shipping_agent_contact_email" type="email" /></label><label>Container Booking Number<input name="booking_number" /></label><label>Container Number<input name="container_number" required /></label><label>Vessel Name<input name="vessel_name" /></label><label>Arrival Port<input name="arrival_port" /></label></div></fieldset><fieldset><legend>Schedule</legend><div className="form-grid"><label>Expected Loading Date<input name="expected_loading_date" type="date" /></label><label>Actual Loading Date<input name="actual_loading_date" type="date" /></label><label>Expected Vessel Departure Date<input name="expected_vessel_departure_date" type="date" /></label><label>Actual Vessel Departure Date<input name="actual_vessel_departure_date" type="date" /></label><label>Expected Arrival Date<input name="expected_arrival_date" type="date" /></label><label>Actual Arrival Date<input name="actual_arrival_date" type="date" /></label></div></fieldset><fieldset><legend>Tariff Broker</legend><div className="form-grid"><label>Tariff Broker Agency<input name="tariff_broker_agency" /></label><label>Broker Contact Name<input name="broker_contact_name" /></label><label>Broker Contact Email<input name="broker_contact_email" type="email" /></label></div></fieldset><div className="form-actions"><button className="primary-action" disabled={isPending} type="submit">{isPending ? "Creating..." : "Create Container"}</button><a className="secondary-action secondary-action--light" href="/?module=purchasing">Cancel</a></div></form></section>;
}
