import Link from "next/link";
import { dateLabel, money, numberFormatter } from "@/lib/formatters";
import { ContainerLoadingSheetControls } from "./container-loading-sheet-controls";
import { reportMappingFor, type ReportFieldMapping } from "@/lib/report-settings";

type Container = { id: string; container_number: string; booking_number: string | null; shipping_agency: string | null; vessel_name: string | null; etd: string | null; eta: string | null; arrival_port: string | null; consolidation_loading_site: string | null; consolidation_loading_address: string | null; container_status: string };
type Line = { id: string; vendor_id: string; vendor_name: string; vendor_email: string | null; po_number: string; sku: string; name: string; hs_code: string | null; quantity_packed: number; pieces_per_carton: number; packing_dimensions: string[]; unit_cbm: number | null; line_cbm: number | null; quantity_boxes: number; unit_cost: number };
type VendorGroup = { id: string; name: string; email: string | null; lines: Line[] };
type ExportType = "packing_list" | "vendor_invoice" | "vendor_product_list";

const cbm = (value: number | null) => value === null ? "Not set" : `${value.toLocaleString("en-US", { minimumFractionDigits: 3, maximumFractionDigits: 6 })} m³`;

export function ContainerLoadingSheetPage({ container, lines, reportMappings, selectedVendorId, exportType }: { container: Container | null; lines: Line[]; reportMappings: ReportFieldMapping[]; selectedVendorId?: string; exportType?: string }) {
  if (!container) return <section className="dashboard-panel"><div className="form-alert">Container was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;
  const baseHref = `/?module=container-loading-sheets&container=${container.id}`;
  const groups = new Map<string, VendorGroup>();
  for (const line of lines) { const group = groups.get(line.vendor_id) ?? { id: line.vendor_id, name: line.vendor_name, email: line.vendor_email, lines: [] }; group.lines.push(line); groups.set(line.vendor_id, group); }
  const vendors = [...groups.values()].sort((left, right) => left.name.localeCompare(right.name));
  const selectedVendor = selectedVendorId ? groups.get(selectedVendorId) ?? null : null;
  const booked = container.container_status === "booked";
  const requestedExport = exportType === "vendor_product_list" || exportType === "vendor_invoice" || exportType === "packing_list" ? exportType : null;

  if (booked) return <BookedLoadingSheet baseHref={baseHref} container={container} reportMappings={reportMappings} selectedVendor={selectedVendor} vendors={vendors} />;
  if (requestedExport === "packing_list") return <PackingList baseHref={baseHref} container={container} lines={lines} reportMappings={reportMappings} />;
  if (selectedVendor && requestedExport === "vendor_product_list") return <VendorProductList baseHref={baseHref} container={container} reportMappings={reportMappings} vendor={selectedVendor} />;
  if (selectedVendor && requestedExport === "vendor_invoice") return <VendorInvoice baseHref={baseHref} container={container} vendor={selectedVendor} />;
  return <PostBookingExportIndex baseHref={baseHref} container={container} vendors={vendors} />;
}

function BookedLoadingSheet({ baseHref, container, reportMappings, selectedVendor, vendors }: { baseHref: string; container: Container; reportMappings: ReportFieldMapping[]; selectedVendor: VendorGroup | null; vendors: VendorGroup[] }) {
  if (selectedVendor) {
    const totals = totalsFor(selectedVendor.lines);
    return <section className="quote-document-page"><div className="quote-document-controls"><Link className="secondary-action" href={baseHref}>Back to Vendor Loading Sheets</Link><ContainerLoadingSheetControls containerNumber={container.container_number} recipientEmail={selectedVendor.email} vendorName={selectedVendor.name} /></div><article className="quote-document loading-sheet"><DocumentHeader container={container} subtitle={selectedVendor.name} title="Container Loading Sheet" /><section className="loading-site-callout"><span>Send Products To</span><strong>{container.consolidation_loading_site || "Loading site not set"}</strong><p className="preserve-lines">{container.consolidation_loading_address || "Please contact the purchasing team for loading instructions."}</p></section><ProductTable lines={selectedVendor.lines} reportMappings={reportMappings} /><Totals totals={totals} /></article></section>;
  }
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Container Shipment</span><h2>Vendor Loading Sheets</h2><p>{container.container_number} · Select a vendor to download or email its product loading list.</p></div><Link className="secondary-action secondary-action--light" href={`/?module=container-detail&container=${container.id}`}>Back to Container</Link></section><article className="data-section"><div className="section-title"><h3>Vendors in Container</h3><span>{vendors.length}</span></div><VendorTable vendors={vendors} renderActions={(vendor) => <Link className="text-action" href={`${baseHref}&loading_vendor=${vendor.id}`}>Export Loading Sheet</Link>} /></article></section>;
}

function PostBookingExportIndex({ baseHref, container, vendors }: { baseHref: string; container: Container; vendors: VendorGroup[] }) {
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Container Shipment</span><h2>Export Loading Data</h2><p>{container.container_number} · Download final loading, packing, and supplier invoice data.</p></div><div className="form-actions"><Link className="primary-action" href={`${baseHref}&export_type=packing_list`}>Download Complete Packing List</Link><Link className="secondary-action secondary-action--light" href={`/?module=container-detail&container=${container.id}`}>Back to Container</Link></div></section><article className="data-section"><div className="section-title"><h3>Vendor Export Data</h3><span>{vendors.length}</span></div><VendorTable vendors={vendors} renderActions={(vendor) => <div className="section-actions"><Link className="text-action" href={`${baseHref}&loading_vendor=${vendor.id}&export_type=vendor_product_list`}>Loaded Product List</Link><Link className="text-action" href={`${baseHref}&loading_vendor=${vendor.id}&export_type=vendor_invoice`}>Product Invoice</Link></div>} /></article></section>;
}

function VendorProductList({ baseHref, container, reportMappings, vendor }: { baseHref: string; container: Container; reportMappings: ReportFieldMapping[]; vendor: VendorGroup }) {
  return <section className="quote-document-page"><div className="quote-document-controls"><Link className="secondary-action" href={baseHref}>Back to Export Loading Data</Link><ContainerLoadingSheetControls containerNumber={container.container_number} downloadLabel="Download Loaded Product List PDF" recipientEmail={null} vendorName={vendor.name} /></div><article className="quote-document loading-sheet"><DocumentHeader container={container} subtitle={vendor.name} title="Loaded Product List" /><ProductTable lines={vendor.lines} reportMappings={reportMappings} /><Totals totals={totalsFor(vendor.lines)} /></article></section>;
}

function VendorInvoice({ baseHref, container, vendor }: { baseHref: string; container: Container; vendor: VendorGroup }) {
  const total = vendor.lines.reduce((sum, line) => sum + line.quantity_packed * line.unit_cost, 0);
  return <section className="quote-document-page"><div className="quote-document-controls"><Link className="secondary-action" href={baseHref}>Back to Export Loading Data</Link><ContainerLoadingSheetControls containerNumber={container.container_number} downloadLabel="Download Product Invoice PDF" recipientEmail={null} vendorName={vendor.name} /></div><article className="quote-document loading-sheet"><DocumentHeader container={container} subtitle={vendor.name} title="Product Invoice" /><section className="loading-sheet-products"><h3>Loaded Products</h3><table className="quote-document-table"><thead><tr><th>PO #</th><th>SKU</th><th>Product</th><th>Qty</th><th>Unit Cost</th><th>Line Total</th></tr></thead><tbody>{vendor.lines.map((line) => <tr key={line.id}><td>{line.po_number}</td><td>{line.sku}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_packed)}</td><td>{money(line.unit_cost)}</td><td>{money(line.quantity_packed * line.unit_cost)}</td></tr>)}</tbody></table></section><div className="quote-document-total"><span>Invoice Total</span><strong>{money(total)}</strong></div></article></section>;
}

function PackingList({ baseHref, container, lines, reportMappings }: { baseHref: string; container: Container; lines: Line[]; reportMappings: ReportFieldMapping[] }) {
  const totals = totalsFor(lines);
  const hsLabel = reportMappingFor(reportMappings, "container_packing_list", "hs_code")?.display_label ?? "HS";
  return <section className="quote-document-page"><div className="quote-document-controls"><Link className="secondary-action" href={baseHref}>Back to Export Loading Data</Link><ContainerLoadingSheetControls containerNumber={container.container_number} downloadLabel="Download Complete Packing List PDF" recipientEmail={null} vendorName="" /></div><article className="quote-document loading-sheet"><DocumentHeader container={container} title="Complete Container Packing List" /><section className="loading-sheet-products"><h3>Loaded Products</h3><table className="quote-document-table"><thead><tr><th>PO #</th><th>Vendor</th><th>SKU</th><th>{hsLabel}</th><th>Product</th><th>Qty</th><th>Pcs/Ctn</th><th>Packing W × D × H</th><th>Unit CBM</th><th>Line CBM</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id}><td>{line.po_number}</td><td>{line.vendor_name}</td><td>{line.sku}</td><td>{line.hs_code || "Not set"}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_packed)}</td><td>{numberFormatter.format(line.pieces_per_carton)}</td><td>{dimensions(line)}</td><td>{cbm(line.unit_cbm)}</td><td>{cbm(line.line_cbm)}</td></tr>)}</tbody></table></section><Totals totals={totals} /></article></section>;
}

function DocumentHeader({ container, subtitle, title }: { container: Container; subtitle?: string; title: string }) {
  return <header className="quote-document-header loading-sheet-header"><div><span className="eyebrow">Terracotta Designs and Kanova &amp; Co.</span><h2>{title}</h2>{subtitle ? <p>{subtitle}</p> : null}</div><dl className="loading-sheet-metadata"><div><dt>Container</dt><dd>{container.container_number}</dd></div><div><dt>Booking Number</dt><dd>{container.booking_number || "Not set"}</dd></div><div><dt>Shipping Agency</dt><dd>{container.shipping_agency || "Not set"}</dd></div><div><dt>Vessel</dt><dd>{container.vessel_name || "Not set"}</dd></div><div><dt>Expected Departure</dt><dd>{dateLabel(container.etd)}</dd></div><div><dt>Expected Arrival</dt><dd>{dateLabel(container.eta)}</dd></div><div><dt>Arrival Port</dt><dd>{container.arrival_port || "Not set"}</dd></div></dl></header>;
}

function ProductTable({ lines, reportMappings }: { lines: Line[]; reportMappings: ReportFieldMapping[] }) { const hsLabel = reportMappingFor(reportMappings, "container_packing_list", "hs_code")?.display_label ?? "HS"; return <section className="loading-sheet-products"><h3>Products to Load</h3><table className="quote-document-table"><thead><tr><th>PO #</th><th>SKU</th><th>{hsLabel}</th><th>Product</th><th>Qty</th><th>Pcs/Ctn</th><th>Packing W × D × H</th><th>Unit CBM</th><th>Line CBM</th></tr></thead><tbody>{lines.map((line) => <tr key={line.id}><td>{line.po_number}</td><td>{line.sku}</td><td>{line.hs_code || "Not set"}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_packed)}</td><td>{numberFormatter.format(line.pieces_per_carton)}</td><td>{dimensions(line)}</td><td>{cbm(line.unit_cbm)}</td><td>{cbm(line.line_cbm)}</td></tr>)}</tbody></table></section>; }
function VendorTable({ renderActions, vendors }: { renderActions: (vendor: VendorGroup) => React.ReactNode; vendors: VendorGroup[] }) { return vendors.length ? <div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Email</th><th>Product Lines</th><th>Loaded Qty</th><th>CBM</th><th>Action</th></tr></thead><tbody>{vendors.map((vendor) => <tr key={vendor.id}><td>{vendor.name}</td><td>{vendor.email || "Not set"}</td><td>{numberFormatter.format(vendor.lines.length)}</td><td>{numberFormatter.format(vendor.lines.reduce((sum, line) => sum + line.quantity_packed, 0))}</td><td>{cbm(vendor.lines.reduce((sum, line) => sum + (line.line_cbm ?? 0), 0))}</td><td>{renderActions(vendor)}</td></tr>)}</tbody></table></div> : <p className="fieldset-note">No vendor products have been loaded into this container.</p>; }
function Totals({ totals }: { totals: { boxes: number; cbm: number; quantity: number } }) { return <><div className="quote-document-total"><span>Total Qty to Load</span><strong>{numberFormatter.format(totals.quantity)}</strong></div><div className="quote-document-total"><span>Total Qty of Boxes</span><strong>{numberFormatter.format(totals.boxes)}</strong></div><div className="quote-document-total"><span>Total CBM</span><strong>{cbm(totals.cbm)}</strong></div></>; }
function dimensions(line: Line) { return line.packing_dimensions.length ? line.packing_dimensions.map((dimension) => <div key={dimension}>{dimension}</div>) : "Not set"; }
function totalsFor(lines: Line[]) { return { boxes: lines.reduce((sum, line) => sum + line.quantity_boxes, 0), cbm: lines.reduce((sum, line) => sum + (line.line_cbm ?? 0), 0), quantity: lines.reduce((sum, line) => sum + line.quantity_packed, 0) }; }
