"use client";

import { useState, useTransition } from "react";
import { dateLabel, money, numberFormatter } from "@/lib/formatters";
import { ConfirmRemoveButton } from "@/components/ui/confirm-remove-button";

type Result = { destination?: string; error?: string };
type FormAction = (formData: FormData) => void | Promise<void>;
type Container = { id: string; container_number: string; booking_number: string | null; shipping_agency: string | null; shipping_agent_contact_name: string | null; shipping_agent_contact_email: string | null; vessel_name: string | null; expected_loading_date: string | null; actual_loading_date: string | null; etd: string | null; actual_vessel_departure_date: string | null; arrival_port: string | null; eta: string | null; arrival_date: string | null; tariff_broker_agency: string | null; broker_contact_name: string | null; broker_contact_email: string | null; container_status: string };
type PurchaseOrder = { id: string; vendor_po_number: string; vendor_name_snapshot: string; status: string };
type SelectedLine = { id: string; sku: string; name: string; quantity_available: number; unit_cost: number };
type Document = { id: string; document_type: string; display_name: string | null; original_file_name: string; uploaded_at: string; signed_url: string | null };
type Agency = { id: string; business_type: string; agency_name: string; contact_name: string | null; contact_email: string | null };

const documentLabels: Record<string, string> = { arrival_notice: "Arrival Notice", bill_of_lading: "Bill of Lading", customs_invoice: "Customs Invoice", delivery_order: "Delivery Order", isf_info: "ISF Info", other: "Other", sea_freight_invoice: "Sea Freight Invoice", trucking_invoice: "Trucking Invoice" };

export function ContainerWorkspace({ activeOrders, addProductAction, agencies, container, containerLines, deleteDocumentAction, documents, editingSection, error: initialError, selectedLines, selectedOrder, updateHeaderAction, uploadDocumentAction }: { activeOrders: PurchaseOrder[]; addProductAction: (formData: FormData) => Promise<Result>; agencies: Agency[]; container: Container | null; containerLines: { id: string; sku: string; name: string; quantity_packed: number; packing_dimensions: string[]; unit_cbm: number | null; line_cbm: number | null; quantity_boxes: number }[]; deleteDocumentAction: FormAction; documents: Document[]; editingSection?: "shipping" | "schedule" | "broker"; error?: string; selectedLines: SelectedLine[]; selectedOrder: PurchaseOrder | null; updateHeaderAction: FormAction; uploadDocumentAction: FormAction }) {
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [brokerAgencyId, setBrokerAgencyId] = useState("");
  const [brokerAgencyName, setBrokerAgencyName] = useState(container?.tariff_broker_agency ?? "");
  const [brokerContactName, setBrokerContactName] = useState(container?.broker_contact_name ?? "");
  const [brokerContactEmail, setBrokerContactEmail] = useState(container?.broker_contact_email ?? "");
  if (!container) return <section className="dashboard-panel"><div className="form-alert">Container was not found.</div><a className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</a></section>;

  const workspaceHref = `/?module=container&container=${container.id}`;
  const addLine = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const formData = new FormData(event.currentTarget); startTransition(async () => { setError(null); const result = await addProductAction(formData); if (result.error) setError(result.error); else if (result.destination) window.location.assign(result.destination); }); };
  const sectionHref = (section: "shipping" | "schedule" | "broker") => `${workspaceHref}&container_edit=${section}`;
  const dateValue = (value: string | null) => value ?? "";
  const brokerAgencies = agencies.filter((agency) => agency.business_type === "customs_broker");
  const cbm = (value: number | null) => value === null ? "Not set" : `${value.toLocaleString("en-US", { minimumFractionDigits: 3, maximumFractionDigits: 6 })} m³`;
  const loadedTotals = { boxes: containerLines.reduce((sum, line) => sum + line.quantity_boxes, 0), cbm: containerLines.reduce((sum, line) => sum + (line.line_cbm ?? 0), 0) };

  return <section className="dashboard-panel">
    <section className="form-header"><div><span className="eyebrow">Container Shipment</span><h2>{container.container_number}</h2><p>{container.shipping_agency || "Shipping agency not set"} · {container.vessel_name || "Vessel not set"}</p></div><a className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</a></section>
    {initialError || error ? <div className="form-alert">{error ?? decodeURIComponent(initialError ?? "")}</div> : null}
    <section className="detail-grid">
      <article className="info-panel"><div className="section-title"><h3>Shipping Details</h3>{editingSection === "shipping" ? <a className="text-action" href={workspaceHref}>Cancel</a> : <a className="text-action" href={sectionHref("shipping")}>Edit</a>}</div>{editingSection === "shipping" ? <form action={updateHeaderAction} className="customer-form"><input name="container_id" type="hidden" value={container.id} /><input name="section" type="hidden" value="shipping" /><div className="form-grid"><label>Booking Number<input defaultValue={container.booking_number ?? ""} name="booking_number" /></label><label>Shipping Agency<input defaultValue={container.shipping_agency ?? ""} name="shipping_agency" /></label><label>Agent Contact<input defaultValue={container.shipping_agent_contact_name ?? ""} name="shipping_agent_contact_name" /></label><label>Agent Email<input defaultValue={container.shipping_agent_contact_email ?? ""} name="shipping_agent_contact_email" type="email" /></label><label>Vessel<input defaultValue={container.vessel_name ?? ""} name="vessel_name" /></label><label>Arrival Port<input defaultValue={container.arrival_port ?? ""} name="arrival_port" /></label></div><div className="form-actions"><button className="primary-action" type="submit">Save Shipping Details</button></div></form> : <dl><div><dt>Booking Number</dt><dd>{container.booking_number || "Not set"}</dd></div><div><dt>Shipping Agent</dt><dd>{container.shipping_agency || "Not set"}</dd></div><div><dt>Agent Contact</dt><dd>{container.shipping_agent_contact_name || "Not set"}</dd></div><div><dt>Agent Email</dt><dd>{container.shipping_agent_contact_email || "Not set"}</dd></div><div><dt>Vessel</dt><dd>{container.vessel_name || "Not set"}</dd></div><div><dt>Arrival Port</dt><dd>{container.arrival_port || "Not set"}</dd></div></dl>}</article>
      <article className="info-panel"><div className="section-title"><h3>Schedule</h3>{editingSection === "schedule" ? <a className="text-action" href={workspaceHref}>Cancel</a> : <a className="text-action" href={sectionHref("schedule")}>Edit</a>}</div>{editingSection === "schedule" ? <form action={updateHeaderAction} className="customer-form"><input name="container_id" type="hidden" value={container.id} /><input name="section" type="hidden" value="schedule" /><div className="form-grid"><label>Expected Loading<input defaultValue={dateValue(container.expected_loading_date)} name="expected_loading_date" type="date" /></label><label>Actual Loading<input defaultValue={dateValue(container.actual_loading_date)} name="actual_loading_date" type="date" /></label><label>Expected Departure<input defaultValue={dateValue(container.etd)} name="expected_vessel_departure_date" type="date" /></label><label>Actual Departure<input defaultValue={dateValue(container.actual_vessel_departure_date)} name="actual_vessel_departure_date" type="date" /></label><label>Expected Arrival<input defaultValue={dateValue(container.eta)} name="expected_arrival_date" type="date" /></label><label>Actual Arrival<input defaultValue={dateValue(container.arrival_date)} name="actual_arrival_date" type="date" /></label></div><div className="form-actions"><button className="primary-action" type="submit">Save Schedule</button></div></form> : <dl><div><dt>Expected Loading</dt><dd>{dateLabel(container.expected_loading_date)}</dd></div><div><dt>Actual Loading</dt><dd>{dateLabel(container.actual_loading_date)}</dd></div><div><dt>Expected Departure</dt><dd>{dateLabel(container.etd)}</dd></div><div><dt>Actual Departure</dt><dd>{dateLabel(container.actual_vessel_departure_date)}</dd></div><div><dt>Expected Arrival</dt><dd>{dateLabel(container.eta)}</dd></div><div><dt>Actual Arrival</dt><dd>{dateLabel(container.arrival_date)}</dd></div></dl>}</article>
      <article className="info-panel"><div className="section-title"><h3>Tariff Broker</h3>{editingSection === "broker" ? <a className="text-action" href={workspaceHref}>Cancel</a> : <a className="text-action" href={sectionHref("broker")}>Edit</a>}</div>{editingSection === "broker" ? <form action={updateHeaderAction} className="customer-form"><input name="container_id" type="hidden" value={container.id} /><input name="section" type="hidden" value="broker" /><input name="tariff_broker_agency" type="hidden" value={brokerAgencyName} /><div className="form-grid"><label>Broker Agency<select onChange={(event) => { const agency = brokerAgencies.find((item) => item.id === event.target.value); setBrokerAgencyId(event.target.value); setBrokerAgencyName(agency?.agency_name ?? ""); setBrokerContactName(agency?.contact_name ?? ""); setBrokerContactEmail(agency?.contact_email ?? ""); }} value={brokerAgencyId}><option value="">Select a customs broker agency</option>{brokerAgencies.map((agency) => <option key={agency.id} value={agency.id}>{agency.agency_name}</option>)}</select></label><label>Broker Contact<input name="broker_contact_name" onChange={(event) => setBrokerContactName(event.target.value)} value={brokerContactName} /></label><label>Broker Email<input name="broker_contact_email" onChange={(event) => setBrokerContactEmail(event.target.value)} type="email" value={brokerContactEmail} /></label></div><div className="form-actions"><button className="primary-action" type="submit">Save Tariff Broker</button></div></form> : <dl><div><dt>Broker Agency</dt><dd>{container.tariff_broker_agency || "Not set"}</dd></div><div><dt>Broker Contact</dt><dd>{container.broker_contact_name || "Not set"}</dd></div><div><dt>Broker Email</dt><dd>{container.broker_contact_email || "Not set"}</dd></div></dl>}</article>
    </section>
    <article className="data-section"><div className="section-title"><h3>Container Documents</h3><span>{documents.length}</span></div><form action={uploadDocumentAction} className="attachment-upload-form attachment-upload-form--product"><input name="container_id" type="hidden" value={container.id} /><label>Document<input accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.jpg,.jpeg,.png" name="container_document_file" required type="file" /></label><label>Type<select defaultValue="bill_of_lading" name="document_type"><option value="bill_of_lading">Bill of Lading</option><option value="isf_info">ISF Info</option><option value="arrival_notice">Arrival Notice</option><option value="sea_freight_invoice">Sea Freight Invoice</option><option value="trucking_invoice">Trucking Invoice</option><option value="customs_invoice">Customs Invoice</option><option value="delivery_order">Delivery Order</option><option value="other">Other</option></select></label><label>Display Name<input name="display_name" placeholder="Optional display name" /></label><button className="small-action" type="submit">Upload Document</button></form>{documents.length ? <div className="table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>File Name</th><th>Uploaded</th><th>Open</th><th>Action</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td>{document.display_name || document.original_file_name}</td><td>{documentLabels[document.document_type] ?? "Other"}</td><td>{document.original_file_name}</td><td>{dateLabel(document.uploaded_at)}</td><td>{document.signed_url ? <a className="text-action" href={document.signed_url} rel="noreferrer" target="_blank">Open</a> : "Unavailable"}</td><td><form action={deleteDocumentAction}><input name="container_id" type="hidden" value={container.id} /><input name="container_document_id" type="hidden" value={document.id} /><ConfirmRemoveButton label="Delete" message={`Delete ${document.original_file_name}? This cannot be undone.`} title="Delete document?" variant="text" /></form></td></tr>)}</tbody></table></div> : <p className="fieldset-note">No container documents have been uploaded.</p>}</article>
    <article className="data-section"><div className="section-title"><h3>Products in Container</h3><span>{containerLines.length}</span></div>{containerLines.length ? <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Qty Loaded</th><th>Packing W × D × H</th><th>Unit CBM</th><th>Line CBM</th></tr></thead><tbody>{containerLines.map((line) => <tr key={line.id}><td>{line.sku}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_packed)}</td><td>{line.packing_dimensions.length ? line.packing_dimensions.map((dimensions) => <div key={dimensions}>{dimensions}</div>) : "Not set"}</td><td>{cbm(line.unit_cbm)}</td><td>{cbm(line.line_cbm)}</td></tr>)}</tbody><tfoot><tr><th className="container-packing-totals" colSpan={6}>Total Qty of Boxes: {numberFormatter.format(loadedTotals.boxes)} &nbsp; | &nbsp; Total CBM: {cbm(loadedTotals.cbm)}</th></tr></tfoot></table></div> : <p className="fieldset-note">Select an active purchase order below to load products into this container.</p>}</article>
    <article className="data-section"><div className="section-title"><h3>Active Purchase Orders</h3><span>{activeOrders.length}</span></div>{activeOrders.length ? <div className="table-wrap"><table><thead><tr><th>PO Number</th><th>Vendor</th><th>Status</th><th>Action</th></tr></thead><tbody>{activeOrders.map((order) => <tr key={order.id}><td>{order.vendor_po_number}</td><td>{order.vendor_name_snapshot}</td><td>{order.status.replaceAll("_", " ")}</td><td><a className="text-action" href={`${workspaceHref}&container_po=${order.id}`}>Import Products</a></td></tr>)}</tbody></table></div> : <p className="fieldset-note">No active purchase orders are available.</p>}</article>
    {selectedOrder ? <article className="data-section"><div className="section-title"><h3>Import Products: {selectedOrder.vendor_po_number}</h3><a className="text-action" href={workspaceHref}>Clear Selection</a></div>{selectedLines.length ? <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Available Qty</th><th>Unit Cost</th><th>Load Qty</th><th>Action</th></tr></thead><tbody>{selectedLines.map((line) => <tr key={line.id}><td>{line.sku}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_available)}</td><td>{money(line.unit_cost)}</td><td><form className="inline-form" id={`container-line-${line.id}`} onSubmit={addLine}><input name="container_id" type="hidden" value={container.id} /><input name="purchase_order_id" type="hidden" value={selectedOrder.id} /><input name="purchase_order_line_id" type="hidden" value={line.id} /><input defaultValue={line.quantity_available} max={line.quantity_available} min="0.001" name="quantity_packed" required step="0.001" type="number" /></form></td><td><button className="text-action text-action--button" disabled={isPending} form={`container-line-${line.id}`} type="submit">{isPending ? "Saving..." : "Add"}</button></td></tr>)}</tbody></table></div> : <p className="fieldset-note">All eligible products from this purchase order have already been loaded or are cancelled.</p>}</article> : null}
  </section>;
}
