"use client";

import { useState, useTransition } from "react";

type Result = { destination?: string; error?: string };
type Agency = { id: string; business_type: string; agency_name: string; address: string | null; contact_name: string | null; contact_email: string | null; contact_phone: string | null; bank_name: string | null; bank_swift_code: string | null; bank_ach_routing_number: string | null; bank_account_number: string | null };

export function PurchasingAgencyEditor({ agency, defaultBusinessType, error, saveAction, deleteAction }: { agency: Agency | null; defaultBusinessType: string; error?: string; saveAction: (formData: FormData) => Promise<Result>; deleteAction: (formData: FormData) => Promise<Result> }) {
  const [formError, setFormError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const type = agency?.business_type ?? defaultBusinessType;
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const formData = new FormData(event.currentTarget); startTransition(async () => { setFormError(null); const result = await saveAction(formData); if (result.error) setFormError(result.error); else if (result.destination) window.location.assign(result.destination); }); };
  const remove = () => startTransition(async () => { setFormError(null); const formData = new FormData(); formData.set("agency_id", agency?.id ?? ""); const result = await deleteAction(formData); if (result.error) setFormError(result.error); else if (result.destination) window.location.assign(result.destination); });
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Purchasing Agency</span><h2>{agency ? agency.agency_name : "Add Agency"}</h2><p>{type === "customs_broker" ? "Customs Broker Agency" : "Shipping Agency"}</p></div><a className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</a></section>{error || formError ? <div className="form-alert">{formError ?? decodeURIComponent(error ?? "")}</div> : null}<form className="customer-form" onSubmit={submit}><input name="agency_id" type="hidden" value={agency?.id ?? ""} /><fieldset><legend>Agency Details</legend><div className="form-grid"><label>Business Type<select defaultValue={type} name="business_type"><option value="shipping">Shipping Agency</option><option value="customs_broker">Customs Broker Agency</option></select></label><label>Agency Name<input defaultValue={agency?.agency_name ?? ""} name="agency_name" required /></label><label>Address<textarea defaultValue={agency?.address ?? ""} name="address" rows={3} /></label><label>Contact Name<input defaultValue={agency?.contact_name ?? ""} name="contact_name" /></label><label>Contact Email<input defaultValue={agency?.contact_email ?? ""} name="contact_email" type="email" /></label><label>Contact Phone<input defaultValue={agency?.contact_phone ?? ""} name="contact_phone" /></label></div></fieldset><fieldset><legend>Payment Bank Information</legend><div className="form-grid"><label>Bank Name<input defaultValue={agency?.bank_name ?? ""} name="bank_name" /></label><label>Bank SWIFT Code<input defaultValue={agency?.bank_swift_code ?? ""} name="bank_swift_code" /></label><label>Bank ACH Route Number<input defaultValue={agency?.bank_ach_routing_number ?? ""} name="bank_ach_routing_number" /></label><label>Bank Account Number<input defaultValue={agency?.bank_account_number ?? ""} name="bank_account_number" /></label></div></fieldset><div className="form-actions"><button className="primary-action" disabled={isPending} type="submit">{isPending ? "Saving..." : "Save Agency"}</button><a className="secondary-action secondary-action--light" href="/?module=purchasing">Cancel</a>{agency ? <button className="text-action text-action--button text-action--danger" disabled={isPending} onClick={remove} type="button">Delete Agency</button> : null}</div></form></section>;
}
