import Link from "next/link";
import { money, numberFormatter } from "@/lib/formatters";
import { PurchaseOrderStatus } from "./purchase-order-status";
import { SubmitPurchaseOrderForReviewButton } from "./submit-purchase-order-for-review-button";

type PurchaseOrder = { id: string; vendor_id: string; vendor_po_number: string; vendor_name: string; currency: string; status: string; po_date: string; expected_ready_date: string | null; expected_ship_date: string | null; expected_arrival_date: string | null; expected_available_date: string | null; freight_amount: number };
type ProductOption = { id: string; sku: string; name: string; vendor_item_number: string; unit_cost: number };
type Line = { id: string; sku: string; name: string; vendor_item_number: string; quantity_ordered: number; unit_cost: number; line_total: number; expected_ready_date: string | null; notes: string | null };

const dateValue = (value: string | null) => value || "Not set";

export function PurchaseOrderLinesEditor({ addLineAction, deleteLineAction, editingLineId, editingSchedule, error, lines, order, products, submitForReviewAction, updateLineAction, updateScheduleAction }: { addLineAction: (formData: FormData) => Promise<void>; deleteLineAction: (formData: FormData) => Promise<void>; editingLineId?: string; editingSchedule: boolean; error?: string; lines: Line[]; order: PurchaseOrder | null; products: ProductOption[]; submitForReviewAction: (formData: FormData) => Promise<{ destination?: string; error?: string }>; updateLineAction: (formData: FormData) => Promise<void>; updateScheduleAction: (formData: FormData) => Promise<void> }) {
  if (!order) return <section className="dashboard-panel"><div className="form-alert">Purchase order was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;

  const editable = order.status === "draft";
  const reviewHref = `/?module=vendor-purchase-order-review&purchase_order=${order.id}`;
  const workspaceHref = `/?module=vendor-purchase-order&purchase_order=${order.id}`;

  return <section className="dashboard-panel">
    <section className="form-header"><div><span className="eyebrow">Purchase Order</span><h2>{order.vendor_po_number}</h2><p><Link className="text-action" href={`/?module=vendor&vendor=${order.vendor_id}`}>{order.vendor_name}</Link> · {order.currency}</p></div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>
    <PurchaseOrderStatus status={order.status} />
    {error ? <div className="form-alert">{decodeURIComponent(error)}</div> : null}
    <section className="detail-grid"><article className="info-panel"><div className="section-title"><h3>Order Schedule</h3>{editable && !editingSchedule ? <Link className="text-action" href={`${workspaceHref}&po_edit=schedule`}>Edit</Link> : null}</div>{editingSchedule ? <form action={updateScheduleAction} className="customer-form"><input name="purchase_order_id" type="hidden" value={order.id} /><div className="form-grid"><label>PO Date<input defaultValue={order.po_date} name="po_date" required type="date" /></label><label>Expected Ready<input defaultValue={order.expected_ready_date ?? ""} name="expected_ready_date" type="date" /></label><label>Expected Ship<input defaultValue={order.expected_ship_date ?? ""} name="expected_ship_date" type="date" /></label><label>Expected Arrival<input defaultValue={order.expected_arrival_date ?? ""} name="expected_arrival_date" type="date" /></label><label>Expected Available<input defaultValue={order.expected_available_date ?? ""} name="expected_available_date" type="date" /></label><label>Expected Freight Cost<input defaultValue={order.freight_amount} min="0" name="freight_amount" step="0.01" type="number" /></label></div><div className="form-actions"><button className="primary-action" type="submit">Save Schedule</button><Link className="secondary-action secondary-action--light" href={workspaceHref}>Cancel</Link></div></form> : <dl><div><dt>PO Date</dt><dd>{dateValue(order.po_date)}</dd></div><div><dt>Expected Ready</dt><dd>{dateValue(order.expected_ready_date)}</dd></div><div><dt>Expected Ship</dt><dd>{dateValue(order.expected_ship_date)}</dd></div><div><dt>Expected Arrival</dt><dd>{dateValue(order.expected_arrival_date)}</dd></div><div><dt>Expected Available</dt><dd>{dateValue(order.expected_available_date)}</dd></div><div><dt>Expected Freight Cost</dt><dd>{money(order.freight_amount)} {order.currency}</dd></div></dl>}</article></section>
    {editable ? <form action={addLineAction} className="customer-form"><input name="purchase_order_id" type="hidden" value={order.id} /><fieldset><legend>Add Product</legend><div className="form-grid"><label>Vendor Product<select name="vendor_product_id" required defaultValue=""><option disabled value="">Select a vendor product</option>{products.map(product => <option key={product.id} value={product.id}>{product.sku} · {product.name} · {money(product.unit_cost)} {order.currency}</option>)}</select></label><label>Quantity<input min="0.001" name="quantity_ordered" required step="0.001" type="number" /></label><label>Expected Ready Date<input defaultValue={order.expected_ready_date ?? ""} name="expected_ready_date" type="date" /></label><label>Line Notes<input name="notes" /></label></div></fieldset><div className="form-actions"><button className="primary-action" disabled={!products.length} type="submit">Add Product</button></div>{!products.length ? <div className="form-alert">This vendor has no active vendor products yet.</div> : null}</form> : null}
    <article className="data-section"><div className="section-title"><h3>Order Products</h3><span>{lines.length}</span></div>{lines.length ? <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Vendor Code</th><th>Product</th><th>Quantity</th><th>Unit Cost</th><th>Line Total</th>{editable ? <th>Action</th> : null}</tr></thead><tbody>{lines.map(line => editingLineId === line.id && editable ? <tr className="po-line-editor-row" key={line.id}><td colSpan={7}><form action={updateLineAction} className="po-line-editor"><input name="purchase_order_id" type="hidden" value={order.id} /><input name="line_id" type="hidden" value={line.id} /><div className="po-line-editor-heading"><div><span className="eyebrow">Edit Product Line</span><strong>{line.sku} · {line.name}</strong></div><span>{line.vendor_item_number}</span></div><div className="po-line-editor-grid"><label>Quantity<input defaultValue={line.quantity_ordered} min="0.001" name="quantity_ordered" required step="0.001" type="number" /></label><label>Expected Ready Date<input defaultValue={line.expected_ready_date ?? ""} name="expected_ready_date" type="date" /></label><label>Line Notes<input defaultValue={line.notes ?? ""} name="notes" /></label></div><div className="form-actions"><button className="primary-action" type="submit">Save Product</button><Link className="secondary-action secondary-action--light" href={workspaceHref}>Cancel</Link></div></form></td></tr> : <tr key={line.id}><td>{line.sku}</td><td>{line.vendor_item_number}</td><td>{line.name}</td><td>{numberFormatter.format(line.quantity_ordered)}</td><td>{money(line.unit_cost)} {order.currency}</td><td>{money(line.line_total)} {order.currency}</td>{editable ? <td><Link className="text-action" href={`${workspaceHref}&po_line=${line.id}`}>Edit</Link><form action={deleteLineAction} className="inline-form"><input name="purchase_order_id" type="hidden" value={order.id} /><input name="line_id" type="hidden" value={line.id} /><button className="text-action text-action--button text-action--danger" type="submit">Delete</button></form></td> : null}</tr>)}</tbody></table></div> : <p className="fieldset-note">Add products to begin building this purchase order.</p>}</article>
    {editable ? <div className="form-actions">{lines.length ? <SubmitPurchaseOrderForReviewButton label="Proceed to Confirm" purchaseOrderId={order.id} submitAction={submitForReviewAction} /> : <span className="fieldset-note">Add at least one product before proceeding to confirmation.</span>}</div> : <div className="form-actions"><Link className="secondary-action secondary-action--light" href={reviewHref}>View Review</Link></div>}
  </section>;
}
