import Link from "next/link";
import { StatusBadge } from "@/components/ui";
import { money, numberFormatter } from "@/lib/formatters";
import type { Product, Vendor } from "./vendor-dashboard";

export function VendorProductDetailPage({ vendor, product }: { vendor: Vendor | null; product: Product | null }) {
  if (!vendor || !product) return <section className="dashboard-panel"><div className="form-alert">Vendor product was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Vendor Product</span><h2>{product.sku} · {product.name}</h2><p>{vendor.name}</p></div><Link className="secondary-action secondary-action--light" href={`/?module=vendor&vendor=${vendor.id}&vendor_tab=products`}>Back to Products</Link></section><section className="detail-grid"><article className="info-panel"><h3>Catalog Data</h3>{product.image_url ? <img alt="" className="product-detail-image" src={product.image_url} /> : null}<dl><div><dt>SKU</dt><dd>{product.sku}</dd></div><div><dt>Product Name</dt><dd>{product.name}</dd></div><div><dt>Product Type</dt><dd>{product.category ?? "Not set"}</dd></div><div><dt>HS Code</dt><dd>{product.hs_code ?? "Not set"}</dd></div><div><dt>Finishes</dt><dd>{product.finishes.join(", ") || "Not set"}</dd></div><div><dt>Dimensions</dt><dd>{product.dimensions.join("; ") || "Not set"}</dd></div></dl></article><article className="info-panel"><div className="section-title"><h3>Vendor Purchasing Data</h3><Link className="text-action" href={`/?module=vendor-product-edit&vendor=${vendor.id}&vendor_product=${product.id}`}>Edit</Link></div><dl><div><dt>Vendor</dt><dd>{vendor.name}</dd></div><div><dt>Vendor Code</dt><dd>{product.vendor_item_number}</dd></div><div><dt>Vendor Product Name</dt><dd>{product.vendor_item_name ?? product.name}</dd></div><div><dt>Unit Price</dt><dd>{money(product.unit_cost)} {product.currency}</dd></div><div><dt>MOQ</dt><dd>{product.minimum_order_quantity === null ? "Not set" : numberFormatter.format(product.minimum_order_quantity)}</dd></div><div><dt>Lead Time</dt><dd>{product.lead_time_days === null ? "Not set" : `${numberFormatter.format(product.lead_time_days)} days`}</dd></div><div><dt>Status</dt><dd><StatusBadge tone={product.is_active ? "good" : "neutral"} value={product.is_active ? "Active" : "Deactivated"} /></dd></div></dl>{product.packing_boxes.length ? <div className="table-wrap"><table><thead><tr><th>Box</th><th>W × D × H</th><th>Net / Gross Weight</th></tr></thead><tbody>{product.packing_boxes.map((box) => <tr key={box.id}><td>{box.label || `Box ${box.sequence}`}</td><td>{[box.width, box.depth, box.height].every((value) => value !== null) ? `${numberFormatter.format(box.width!)} × ${numberFormatter.format(box.depth!)} × ${numberFormatter.format(box.height!)} in` : "Not set"}</td><td>{box.net_weight === null && box.gross_weight === null ? "Not set" : `${box.net_weight ?? "—"} / ${box.gross_weight ?? "—"} lb`}</td></tr>)}</tbody></table></div> : <p>Not set</p>}</article></section></section>;
}
