import Link from "next/link";
import { StatusBadge } from "@/components/ui";
import { money, numberFormatter } from "@/lib/formatters";
import type { Product, Vendor } from "./vendor-dashboard";

export function VendorProductDetailPage({ vendor, product }: { vendor: Vendor | null; product: Product | null }) {
  if (!vendor || !product) return <section className="dashboard-panel"><div className="form-alert">Vendor product was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;
  const dimensions = [product.box_width_inches, product.box_depth_inches, product.box_height_inches].every((value) => value !== null) ? `${numberFormatter.format(product.box_width_inches!)} × ${numberFormatter.format(product.box_depth_inches!)} × ${numberFormatter.format(product.box_height_inches!)} in` : "Not set";
  const weights = product.net_weight_lbs === null && product.gross_weight_lbs === null ? "Not set" : `${product.net_weight_lbs ?? "—"} / ${product.gross_weight_lbs ?? "—"} lb`;
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Vendor Product</span><h2>{product.sku} · {product.name}</h2><p>{vendor.name}</p></div><Link className="secondary-action secondary-action--light" href={`/?module=vendor&vendor=${vendor.id}&vendor_tab=products`}>Back to Products</Link></section><section className="detail-grid"><article className="info-panel"><h3>Catalog Data</h3>{product.image_url ? <img alt="" className="product-detail-image" src={product.image_url} /> : null}<dl><div><dt>SKU</dt><dd>{product.sku}</dd></div><div><dt>Product Name</dt><dd>{product.name}</dd></div><div><dt>Product Type</dt><dd>{product.category ?? "Not set"}</dd></div><div><dt>HS Code</dt><dd>{product.hs_code ?? "Not set"}</dd></div><div><dt>Finishes</dt><dd>{product.finishes.join(", ") || "Not set"}</dd></div><div><dt>Dimensions</dt><dd>{product.dimensions.join("; ") || "Not set"}</dd></div></dl></article><article className="info-panel"><div className="section-title"><h3>Vendor Purchasing Data</h3><Link className="text-action" href={`/?module=vendor-product-edit&vendor=${vendor.id}&vendor_product=${product.id}`}>Edit</Link></div><dl><div><dt>Vendor</dt><dd>{vendor.name}</dd></div><div><dt>Vendor Code</dt><dd>{product.vendor_item_number}</dd></div><div><dt>Vendor Product Name</dt><dd>{product.vendor_item_name ?? product.name}</dd></div><div><dt>Unit Price</dt><dd>{money(product.unit_cost)} {product.currency}</dd></div><div><dt>MOQ</dt><dd>{product.minimum_order_quantity === null ? "Not set" : numberFormatter.format(product.minimum_order_quantity)}</dd></div><div><dt>Lead Time</dt><dd>{product.lead_time_days === null ? "Not set" : `${numberFormatter.format(product.lead_time_days)} days`}</dd></div><div><dt>Vendor Box Dimensions</dt><dd>{dimensions}</dd></div><div><dt>Net / Gross Weight</dt><dd>{weights}</dd></div><div><dt>Status</dt><dd><StatusBadge tone={product.is_active ? "good" : "neutral"} value={product.is_active ? "Active" : "Deactivated"} /></dd></div></dl></article></section></section>;
}
