"use client";

import Link from "next/link";
import { useState } from "react";

export type VendorProductOption = { id: string; sku: string; name: string; category: string | null; box_width: number | null; box_length: number | null; box_height: number | null; net_weight: number | null; gross_weight: number | null };
type Vendor = { id: string; name: string; currency: string; defaultMinimumOrderQuantity: number | null; defaultLeadTimeDays: number | null };
type Fields = Record<string, string>;
const stringValue = (value: number | null | undefined) => value === null || value === undefined ? "" : String(value);

export function VendorProductEditor({ vendor, products, error, saveAction }: { vendor: Vendor | null; products: VendorProductOption[]; error?: string; saveAction: (formData: FormData) => Promise<void> }) {
  const [productId, setProductId] = useState("");
  const [fields, setFields] = useState<Fields>({ lead_time_days: stringValue(vendor?.defaultLeadTimeDays), minimum_order_quantity: stringValue(vendor?.defaultMinimumOrderQuantity), unit_cost: "0" });
  if (!vendor) return <section className="dashboard-panel"><div className="form-alert">Vendor was not found.</div><Link className="secondary-action secondary-action--light" href="/?module=purchasing">Back to Purchasing</Link></section>;
  const selectedProduct = products.find((product) => product.id === productId);
  const setField = (name: string, value: string) => setFields((current) => ({ ...current, [name]: value }));
  const field = (name: string) => ({ name, onChange: (event: React.ChangeEvent<HTMLInputElement>) => setField(name, event.target.value), value: fields[name] ?? "" });
  const selectProduct = (nextProductId: string) => {
    const product = products.find((item) => item.id === nextProductId);
    setProductId(nextProductId);
    if (!product) return;
    setFields((current) => ({ ...current, vendor_item_number: product.sku, vendor_item_name: product.name, product_type: product.category ?? "", box_width_inches: stringValue(product.box_width), box_depth_inches: stringValue(product.box_length), box_height_inches: stringValue(product.box_height), net_weight_lbs: stringValue(product.net_weight), gross_weight_lbs: stringValue(product.gross_weight) }));
  };
  return <section className="dashboard-panel"><section className="form-header"><div><span className="eyebrow">Purchasing Vendor</span><h2>Add Vendor Product</h2><p>Select a system product to import its product data, then refine vendor-specific details before saving.</p></div><Link className="secondary-action secondary-action--light" href={`/?module=vendor&vendor=${vendor.id}&vendor_tab=products`}>Back to Products</Link></section>{error ? <div className="form-alert">{decodeURIComponent(error)}</div> : null}<form action={saveAction} className="customer-form"><input type="hidden" name="vendor_id" value={vendor.id} /><fieldset><legend>System Product</legend><div className="form-grid"><label>Product SKU<select name="product_id" required value={productId} onChange={(event) => selectProduct(event.target.value)}><option disabled value="">Select a system product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.sku} · {product.name}</option>)}</select></label><label>Vendor Code<input required {...field("vendor_item_number")} /></label><label>Vendor Product Name<input {...field("vendor_item_name")} /></label><label>Product Type<input {...field("product_type")} /></label><label>HS Code<input {...field("hs_code")} /></label><label>Price ({vendor.currency})<input min="0" required step="0.0001" type="number" {...field("unit_cost")} /></label><label>MOQ<input min="0.001" step="0.001" type="number" {...field("minimum_order_quantity")} /></label><label>Lead Time (days)<input min="0" type="number" {...field("lead_time_days")} /></label></div></fieldset>{selectedProduct ? <p className="fieldset-note">Imported from {selectedProduct.sku}. The SKU remains tied to the selected system product; vendor-specific values may be adjusted.</p> : null}<fieldset><legend>Packing Details</legend><div className="form-grid"><label>Box Width (in)<input min="0" step="0.001" type="number" {...field("box_width_inches")} /></label><label>Box Depth (in)<input min="0" step="0.001" type="number" {...field("box_depth_inches")} /></label><label>Box Height (in)<input min="0" step="0.001" type="number" {...field("box_height_inches")} /></label><label>Net Weight (lb)<input min="0" step="0.001" type="number" {...field("net_weight_lbs")} /></label><label>Gross Weight (lb)<input min="0" step="0.001" type="number" {...field("gross_weight_lbs")} /></label><label>Status<select name="is_active" defaultValue="true"><option value="true">Active</option><option value="false">Deactivated</option></select></label></div></fieldset><div className="form-actions"><button className="primary-action" type="submit">Save Vendor Product</button><Link className="secondary-action secondary-action--light" href={`/?module=vendor&vendor=${vendor.id}&vendor_tab=products`}>Cancel</Link></div></form></section>;
}
